# Generated by Django 2.1.2 on 2018-12-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_quiz', '0003_auto_20181230_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_modified',
            field=models.DateTimeField(null=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_published',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_modified',
            field=models.DateTimeField(null=True, verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='date_published',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
