# Generated by Django 2.1.2 on 2018-12-31 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rec_quiz', '0004_auto_20181231_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='rec_quiz.Question'),
        ),
    ]
