# Generated by Django 2.1.2 on 2018-12-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec_quiz', '0002_auto_20181230_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='association',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
